### PR TITLE
Structured learning 2

### PR DESCRIPTION
**Pull request by ilastikdev**
Used in pgmlink for the new ilastik Structured Learning Tracking Workflow.

### CODE REVIEW

**Comment by DerThorsten** [comment]
@joergkappes, what do you think

**Comment by joergkappes** [comment]
Please commit in the correct branch, which is learning-experimental.

opengm:master is the wrong branch - please correct me if I am wrong.

**Comment by DerThorsten** [comment]
and synch  learning-experimental with master

**Comment by ilastikdev** [comment]
ilastikdev/opengm-1/structured_learning_2
is synched with learning-experimental and master

**Pull request closed without merging**
