### PR TITLE
Msvc fixes

### PR DESCRIPTION
**Pull request by ilastikdev**
Needed for compiling opengm on MS VC 2012

### CODE REVIEW

**Comment by ilastikdev** [comment]
IsCompleteType did NOT compile on MSVC2012
solution provided uses 
#include <type_traits>
in metaprogramming.hxx
this in turn requires flag -std=gnu++11

with this flag code builds on clang and gcc
and all the tests pass

Question is: can we add newer standard flag?

**Comment by ilastikdev** [comment]
@ukoethe @chaubold 

please review

**Comment by ilastikdev** [comment]
ready to be merged into learning-experimental

**Comment by joergkappes** [comment]
* std::unique_ptr is used without need and should be avoided. (if possible we would be compatible with c++98)
* using long long instead of size_t in omp_parallel_for is only required for older omp-version (the only one supported by VS-compiler). I do not know if it is a good idea to ignore this cast warning everywhere because one single compiler is not up to date ...?!? I am open for suggestions and comments.
* When external libs are broken, please report and we can try to fix this instead of comment these parts out.

**Comment by ukoethe** [comment]
Thanks for looking this over, @joergkappes 

> using long long instead of size_t in omp_parallel_for is only required for older omp-version (the only one supported by VS-compiler). I do not know if it is a good idea to ignore this cast warning everywhere because one single compiler is not up to date ...?!?

On Windows, this is not a warning but an error: Windows only supports **signed** index variables in omp_parallel_for. We think the proposed fix is the easiest solution.

> `std::unique_ptr` is used without need and should be avoided. (if possible we would be compatible with c++98)

We use `std::unique_ptr` because code like 
```
ValueType coeffs[numAssignments];
```
is **illegal** in all versions of C++ when `numAssignments` is not a compile-time constant -- it just happens to be supported as a gcc extension on some platforms. `std::auto_ptr` would work for C++98, but is considered deprecated in C++11 (and issues a warning). I don't think that any compiler we care about doesn't support `std::unique_ptr`.

> When external libs are broken, please report and we can try to fix this instead of comment these parts out.

The problem with those libs is that they get downloaded and possibly compiled even if we **don't need** them for the present installation. If such a download or compilation fails, the **entire** build is stalled. Instead of asking not to comment out libraries that break our build, you might consider to provide a command-line mechanism to disable external libraries we don't need.

**Comment by joergkappes** [comment]
Hi,
a unsigned index variable in omp_parallel_for is valid since OpenMP 3.0. This is also true for the Windows platform, but VS-compiler supports only OpenMP 2.0. So its a fix to be compatible with OpenMP2.0 (and VS). If we agree to want to be compatible with OpenGM2.0 we should additionally fix the unsigned-signed comparison in the same line with an explicit cast, shouldn't we?

Concerning "std::unique_ptr" I would suggest to use "new" and "delete" explicit, than its 100% compatible.

I will try to find some time to make the external lib script more configurable, thanks for the suggestion.

**Comment by ukoethe** [comment]
> Concerning "std::unique_ptr" I would suggest to use "new" and "delete" explicit, than its 100% compatible.

This is a very bad idea, because the code is no longer thread-safe. That is, when the function is terminated by an exception, `delete[]` gets never called -- memory leak. Avoiding this is the point of `std::unique_ptr`! If you insist to avoid `std::unique_ptr`, it is best to write a 5-line utility class which implements just the required functionality (i.e. calls `delete[]` in the destructor).

**Comment by joergkappes** [comment]
Hi,
know I get it, I was totally confused why this should not be thread-safe.
If the code should be exception-safe I would use a std::vector at this part of the code, because it maybe more intuitive. However, the problem exists at several other places in the code, too.

**Comment by joergkappes** [comment]
@ilastikdev : Can U please fix the changes in  src/external/patches/CMakeLists.txt .
Looks like a copy past error. U replaced ConicBundle by IBFS.
If U cannot build ConicBundle comment it out, if it is no problem just revert this change.
I will have a look at external libs next month.

If your done, please send me a mail and I will merge the PR

**Comment by ukoethe** [comment]
Superseded by PR https://github.com/opengm/opengm/pull/457

**Comment by joergkappes** [comment]
PR  #457  merged

**Pull request closed without merging**
